### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by Jackie0911** [Anorov/cloudflare-scrape#118]
I run the example and i get an error like this:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 47, in request
    return self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 90, in solve_cf_challenge
    return self.request(method, redirect.headers["Location"], **original_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 39, in request
    resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 578, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 178, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

what should i do?
thank you

**Comment by Anorov** [comment]
If you do a simple `requests.get(url)` against the URL, do you get the same error?

If yes, then the issue is either with the site or you (probably you), not cloudflare-scrape. I cannot help in that case. Your SSL libraries or Python interpreter could possibly be out-of-date.

If you get a different error, then the problem may be with cloudflare-scrape. If so, please re-open this issue. Thanks.

**Comment by Jackie0911** [comment]
it's certifi lib's problem,I‘m figure out.thank you
