### ISSUE TITLE
has cloudflare changed?

### ISSUE THREAD

**Issue by ezekielincorrigible** [Anorov/cloudflare-scrape#134]
This worked last month:
```
import cfscrape
import mechanicalsoup
scraper = cfscrape.CloudflareScraper()
scraper.get('https://hacked.com/wp-login.php')
tokens = cfscrape.get_tokens('https://hacked.com')
browser = mechanicalsoup.StatefulBrowser(session=scraper, user_agent=tokens[1])
```

but now when trying to get the tokens,

```
>>> scraper = cfscrape.CloudflareScraper()
>>> scraper.get('https://hacked.com/wp-login.php')
<Response [200]>
>>> tokens = cfscrape.get_tokens('https://hacked.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cfscrape/__init__.py", line 173, in get_tokens
    raise ValueError("Unable to find Cloudflare cookies. Does the site actually have Cloudflare IUAM (\"I'm Under Attack Mode\") enabled?")
ValueError: Unable to find Cloudflare cookies. Does the site actually have Cloudflare IUAM ("I'm Under Attack Mode") enabled?
```

but a straight up stateful browser from mechanical soup still fails
```
>>> browser = mechanicalsoup.StatefulBrowser()
>>> browser.get('https://hacked.com/wp-login.php')
<Response [403]>
```

I no longer see the cloudflare loading screen when I manually navigate to that page but there seems to be some kind of antiscraping measure stopping me? This may mean my issue is beyond the scope of this place but any suggestions of advice would be very much appreciated!

**Comment by Anorov** [comment]
The website no longer appears to be using Cloudflare, so unfortunately this is out of the scope of this project. You'll have to find another way to circumvent their anti-bot mechanism.
