### ISSUE TITLE
Some site's it works on some sites it dont.

### ISSUE THREAD

**Issue by djoey123** [Anorov/cloudflare-scrape#144]
Here is the error log

`ERROR:root:Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues.
Traceback (most recent call last):
  File "/root/tester/test.py", line 13, in <module>
    status_code = scraper.get(url).status_code
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cfscrape/__init__.py", line 47, in request
    return self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cfscrape/__init__.py", line 77, in solve_cf_challenge
    params["jschl_answer"] = str(self.solve_challenge(body) + len(domain))
  File "/usr/local/lib/python3.5/dist-packages/cfscrape/__init__.py", line 120, in solve_challenge
    result = node.exec_(js)
  File "/usr/local/lib/python3.5/dist-packages/execjs/_abstract_runtime.py", line 17, in exec_
    return self.compile('', cwd=cwd).exec_(source)
  File "/usr/local/lib/python3.5/dist-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/usr/local/lib/python3.5/dist-packages/execjs/_external_runtime.py", line 87, in _exec_
    output = self._exec_with_pipe(source)
  File "/usr/local/lib/python3.5/dist-packages/execjs/_external_runtime.py", line 108, in _exec_with_pipe
    self._fail_on_non_zero_status(ret, stdoutdata, stderrdata)
  File "/usr/local/lib/python3.5/dist-packages/execjs/_external_runtime.py", line 134, in _fail_on_non_zero_status
    raise ProcessExitedWithNonZeroStatus(status=status, stdout=stdoutdata, stderr=stderrdata)
execjs._exceptions.ProcessExitedWithNonZeroStatus: (1, '', '')`

**Comment by Xonshiz** [comment]
Could you share the website you're trying to scrap and if possible, then some code?

**Comment by djoey123** [comment]
This is my code:

import cfscrape
import sys
import requests
from requests_toolbelt.adapters.source import SourceAddressAdapter

url = sys.argv[1]


#scraper = cfscrape.create_scraper()  # returns a CloudflareScraper instance
scraper = cfscrape.create_scraper()
scraper.mount('http://', SourceAddressAdapter(('myextraip')))
scraper.mount('https://', SourceAddressAdapter(('myextraip')))
status_code = scraper.get(url).status_code

if status_code == 403:
	print("200")

if status_code == 200:
	print("200")

it seems to be fixed now, will test it out to find a other domain with that error.

**Comment by djoey123** [comment]
I think i found the problem, when i use sudo -u www-data python3 test.py linkhere it gives that error

**Comment by Xonshiz** [comment]
Well, if the issue has been solved and it doesn't look like it's not the issue with the script, could you close this issue?

**Comment by djoey123** [comment]
Looks like it is fixed with change the script to www-data group. :)
