### ISSUE TITLE
Cloudflare Issue

### ISSUE THREAD

**Issue by lolippouf2** [Anorov/cloudflare-scrape#149]
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/xxx/xxx/xxx.py", line 279, in run
    self.populate()
  File "/Users/xxx/xxx/xxx.py", line 107, in populate
    r = scraper.get(url,headers=headers)
  File "/Library/Python/2.7/site-packages/requests-2.12.1-py2.7.egg/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/Users/xxx/Library/Python/2.7/lib/python/site-packages/cfscrape/__init__.py", line 66, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/Users/xxx/Library/Python/2.7/lib/python/site-packages/cfscrape/__init__.py", line 97, in solve_cf_challenge
    params["jschl_answer"] = str(self.solve_challenge(body) + len(domain))
  File "/Users/xxx/Library/Python/2.7/lib/python/site-packages/cfscrape/__init__.py", line 127, in solve_challenge
    raise ValueError("Error parsing Cloudflare IUAM Javascript challenge. %s" % BUG_REPORT)
ValueError: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."

Version: 1.9.5

**Comment by Anorov** [comment]
From the traceback, I think you aren't using the latest version (1.9.5).
