### ISSUE TITLE
get_cookie_string() and get_tokens() don't work

### ISSUE THREAD

**Issue by nedark** [Anorov/cloudflare-scrape#168]
However scraper.get() does work.

```
>>> cookie, user_agent = cfscrape.get_cookie_string("https://www.off---white.com/en/LT/men/products/omea180f18d471431088s")
ERROR:root:'https://www.off---white.com/en/LT/men/products/omea180f18d471431088s' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 205, in get_cookie_string
    tokens, user_agent = cls.get_tokens(url, user_agent=user_agent, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 178, in get_tokens
    resp.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.off---white.com/en/LT/men/products/omea180f18d471431088s
```

```
>>> cookie, user_agent = cfscrape.get_tokens("https://www.off---white.com/en/LT/men/products/omea180f18d471431088s")
ERROR:root:'https://www.off---white.com/en/LT/men/products/omea180f18d471431088s' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 178, in get_tokens
    resp.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.off---white.com/en/LT/men/products/omea180f18d471431088s
```

```
>>> scraper = cfscrape.create_scraper()
>>> response = scraper.get("https://www.off---white.com/en/LT/men/products/omea180f18d471431088s")
>>>
```

**Comment by Anorov** [comment]
Thanks, I see the problem and will fix it when I have time this week.

The issue is due to the page returning a Cloudflare CAPTCHA challenge. You
won't be able to use this library (or any other library, else that would
kind of defeat the point of CAPTCHAs) to circumvent it.

**Comment by nedark** [comment]
But why does it return captcha challenge with get_cookie_string()/get_tokens() and not with get()?
