### ISSUE TITLE
PyInstaller and cfscrape

### ISSUE THREAD

**Issue by noembryo** [Anorov/cloudflare-scrape#178]
Is there a way to use cfscrape with PyInstaller?
Although it works when using it in a script, building the same script with PyInstaller produces this error:
```
  File "main.py", line 1312, in on_check_btn_clicked
  File "site-packages\requests\sessions.py", line 537, in get
  File "site-packages\cfscrape\__init__.py", line 68, in request
  File "site-packages\cfscrape\__init__.py", line 97, in solve_cf_challenge
  File "site-packages\cfscrape\__init__.py", line 134, in solve_challenge
  File "subprocess.py", line 216, in check_output
  File "subprocess.py", line 386, in __init__
  File "subprocess.py", line 519, in _get_handles
  File "subprocess.py", line 570, in _make_inheritable
WindowsError: [Error 6] The handle is invalid
```
Are there any hooks for it? because there aren't any in the `hooks` dir of PyInstaller's installation.
Any help will be greatly appreciated..

**Comment by Anorov** [comment]
Can you please try upgrading cloudflare-scrape with `pip install -U cfscrape` and see if you continue to experience this problem? If so, please re-open this issue.

**Comment by dr-nyt** [comment]
I tried updating updating like you suggested but it still doesnt work. When running the executable, it brings up a popup message saying: `failed to execute script`

Accessing the logs shows this:
```
Traceback (most recent call last):
    File "run.py", line 9, in <module>
    File "<frozen importlib.__bootstrap>", line 983, in _find_and_load
    File "<frozen importlib.__bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib.__bootstrap>", line 667, in _load_unlocked
    File "C:\users\super\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
        exec(bytecode, module.__dict__)
    File "site-package\cfscrape\__init__.py", line 26, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\super\\AppData\\Local\\Temp\\_MEI345122\\cfscrape\\user_agents.json'
[32296] Failed to execute script run
```

**Comment by dr-nyt** [comment]
Nvm, I managed to fix it by copying the cfscrape folder in the python 3 directory to the same folder as my executable.

**Comment by pro-src** [comment]
Hi @dr-nyt 

Please see https://github.com/Anorov/cloudflare-scrape/issues/237

**Comment by dr-nyt** [comment]
Thanx, that makes more sense :)
