### ISSUE TITLE
New Cfscrape CF bypass issue

### ISSUE THREAD

**Issue by Siskas** [Anorov/cloudflare-scrape#182]
Hi, 

I’ve tried bypassing a CF protection, and it doesn’t seem to work anymore.
I’m up to date (1.9.5) and coding under iOS 12 on Pythonista, but this hasn’t been an issue so far (last try was in mid November and was alright).

For example, if I type 
```
import cfscrape
scpr=cfscrape.create_scraper()
scpr.get(“https://tether.to/“)
```

I get as a result a Permission Error as follows (a bit unreadable here, sorry for that): 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  
File "/var/containers/Bundle/Application/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/sessions.py", line 481, in get
    return self.request('GET', url, **kwargs)
  
File "/private/var/mobile/Containers/Shared/AppGroup/Pythonista3/Documents/site-packages-3/cfscrape/__init__.py", line 68, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  
File "/private/var/mobile/Containers/Shared/AppGroup/Pythonista3/Documents/site-packages-3/cfscrape/__init__.py", line 97, in solve_cf_challenge
    params["jschl_answer"] = self.solve_challenge(body, domain)
  
File "/private/var/mobile/Containers/Shared/AppGroup/Pythonista3/Documents/site-packages-3/cfscrape/__init__.py", line 134, in solve_challenge
    result = subprocess.check_output(["node", "-e", js]).strip()
  
File "/var/containers/Bundle/Application/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/subprocess.py", line 337, in check_output
    **kwargs).stdout
  
File "/var/containers/Bundle/Application/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/subprocess.py", line 404, in run
    with Popen(*popenargs, **kwargs) as process:
  
File "/var/containers/Bundle/Application/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/subprocess.py", line 708, in __init__
    restore_signals, start_new_session)
  
File "/var/containers/Bundle/Application/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/subprocess.py", line 1261, in _execute_child
    restore_signals, start_new_session, preexec_fn)

PermissionError: [Errno 1] Operation not permitted
```

It seems to me that the issue may be there:
```
cfscrape/__init__.py", line 134, in solve_challenge
    result = subprocess.check_output(["node", "-e", js]).strip()
```

Any of you getting similar issues?
I reckon it may be the yearly CF update of its anti bot system.

SIskas

**Comment by Mattwmaster58** [comment]
> I’m up to date (1.9.5) and coding under iOS 12 on Pythonista

You can't run shell commands on iOS, much less install Node.js

**Comment by Siskas** [comment]
I’m aware of this.

However, it ran without any issue so far, and neither my version nor my dev environment changed.
So I’m wondering what might have changed in the meantime.

**Comment by lukastribus** [comment]
I assume you used cloudflare-scrape when it didn't require nodejs, but used js2py instead.

Before:
https://github.com/Anorov/cloudflare-scrape/commit/0e39950301c6319475f3076dedfcee1a86cc7d8e

Also see:
https://github.com/Anorov/cloudflare-scrape/issues/180

Now that it requires nodejs, your setup doesn't work anymore. This is not triggered by Cloudflare itself.

**Comment by Anorov** [comment]
Please re-open this issue if you're still continuing to experience this error.
