### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by sarsky22** [Anorov/cloudflare-scrape#186]
I tried 5 minutes ago : 
url = "https://c.japscan.to/lel/Sun-Ken-Rock/Volume-1/SKR_001.jpg"
cfurl = scraper.get(url).content
Everything worked fine
Now there is this error : 
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python37\lib\site-packages\cfscrape\__init__.py", line 68, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "C:\Python37\lib\site-packages\cfscrape\__init__.py", line 97, in solve_cf_challenge
    params["jschl_answer"] = self.solve_challenge(body, domain)
  File "C:\Python37\lib\site-packages\cfscrape\__init__.py", line 134, in solve_challenge
    result = subprocess.check_output(["node", "-e", js]).strip()
  File "C:\Python37\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Python37\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python37\lib\subprocess.py", line 728, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Python37\lib\subprocess.py", line 1040, in _get_handles
    p2cread = self._make_inheritable(p2cread)
  File "C:\Python37\lib\subprocess.py", line 1090, in _make_inheritable
    _winapi.DUPLICATE_SAME_ACCESS)
OSError: [WinError 6] Descripteur non valide

I guess japscan did something, but I can't clearly see what. Any idea ?

**Comment by pro-src** [comment]
@sarsky22, this is an OS(Windows) error related to subprocess creation. Since nobody else appears to be experiencing this problem, my guess is that you have something misconfigured on your system. It could be a faulty python installation. Try reinstalling python.

Recommendation: Don't use Microsoft products.

**Comment by pro-src** [comment]
@sarsky22 or it could be a problem with python... I just did a quick search: https://bugs.python.org/issue3905

In that issue the error is only reproducible if you launch the process from a desktop shortcut. Is that what you're doing? If so, format your OS. As a matter of fact, do that anyway then do it again. :laughing:

**Comment by Anorov** [comment]
Can you please try upgrading cloudflare-scrape with `pip install -U cfscrape` and see if you continue to experience this issue?
