### ISSUE TITLE
No longer working for me on nsfw site

### ISSUE THREAD

**Issue by ohura88** [Anorov/cloudflare-scrape#192]
There is a particular NSFW site that I have a bot running to scrape pages from. Today the bot stopped functioning. It looks like some change from Cloudflare is the culprit.

Here is the source of the page, the url is listed at the top of the paste: https://pastebin.com/Hp4tavEA

Here is the stacktrace:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ohura\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\ohura\AppData\Local\Programs\Python\Python36\lib\site-packages\cfscrape\__init__.py", line 68, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "C:\Users\ohura\AppData\Local\Programs\Python\Python36\lib\site-packages\cfscrape\__init__.py", line 97, in solve_cf_challenge
    params["jschl_answer"] = self.solve_challenge(body, domain)
  File "C:\Users\ohura\AppData\Local\Programs\Python\Python36\lib\site-packages\cfscrape\__init__.py", line 128, in solve_challenge
    raise ValueError("Error parsing Cloudflare IUAM Javascript challenge. %s" % BUG_REPORT)
ValueError: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

Here is my version of cfscrape:

`C:\Users\ohura>pip show cfscrape
Name: cfscrape
Version: 1.9.5`

Sorry that it had to be an NSFW page but that's where I'm using your library.

**Comment by armin884** [comment]
Same error here...
```
  File "build\bdist.win32\egg\cfscrape\__init__.py", line 177, in get_tokens
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "build\bdist.win32\egg\cfscrape\__init__.py", line 68, in request
  File "build\bdist.win32\egg\cfscrape\__init__.py", line 97, in solve_cf_challenge
  File "build\bdist.win32\egg\cfscrape\__init__.py", line 127, in solve_challenge

ValueError: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.
Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."
```

**Comment by washedev** [comment]
An exception occured: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

**Comment by xiconet** [comment]
Hi
Same problem here, due to a change in the "challenge" code. I'm not very good at regexp, unfortunately

**Comment by xiconet** [comment]
My mistake, I wasn't using the latest version which is still correctly solving the "challenge" in my case.
A very nice tool, indeed.
