### ISSUE TITLE
Error when trying to use comic_dl with readcomiconline.to

### ISSUE THREAD

**Issue by sharweezy** [Anorov/cloudflare-scrape#201]
Hello, 
As of today, I have been receiving this error when trying to use the comic_dl application with readcomiconline.to. I have already updated cfscrape to ver. 1.9.6 and pip to ver. 19.0.3.

Edit: updated cfscrape to ver. 1.9.7, same error.

The website has a different captcha than what I have been used to seeing, and I thought I should raise awareness to the issue below. 

Fooling CloudFlare...Please Wait...
Traceback (most recent call last):
  File "comic_dl\__main__.py", line 10, in <module>
  File "comic_dl\comic_dl.py", line 237, in __init__
  File "comic_dl\honcho.py", line 101, in checker
  File "comic_dl\sites\readcomicOnlineto.py", line 36, in __init__
  File "comic_dl\sites\readcomicOnlineto.py", line 43, in single_chapter
  File "comic_dl\globalFunctions.py", line 38, in page_downloader
  File "site-packages\requests\sessions.py", line 525, in get
  File "site-packages\cfscrape\__init__.py", line 68, in request
  File "site-packages\cfscrape\__init__.py", line 97, in solve_cf_challenge
  File "site-packages\cfscrape\__init__.py", line 127, in solve_challenge
ValueError: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."
[14300] Failed to execute script __main__

**Comment by pro-src** [comment]
@sharweezy Once you read https://github.com/Anorov/cloudflare-scrape#updates I'm sure somebody will be happy to help you.

**Comment by EdmundMartin** [comment]
Just tested with 1.9.7 on my machine and not encountering the error. The version of the Cloudflare captcha looks the same from what I can see. The different image etc, is due to the fact the site is using Cloudflare premium which allows you to change the look of the challenge page.

**Comment by sharweezy** [comment]
Hello all and thanks for the reply,

I am still encountering the issue even after performing the update steps at https://github.com/Anorov/cloudflare-scrape#updates

But, yes, I will try my best to follow the proper steps to open an issue.

**Comment by edimusxero** [comment]
I too am getting the same error after updating.  It looks like readcomiconline.to changed something as their site wasn't working at all yesterday

**Comment by sharweezy** [comment]
Yes! Something has definitely changed. You no longer see the running little batman animation when they first check your browser. Today I am able to view the comics through the website, but it seems comic_dl can't find its way around the Cloudflare.
