### ISSUE TITLE
TypeError: Cannot read property 'charCodeAt' of undefined

### ISSUE THREAD

**Issue by ozmartian** [Anorov/cloudflare-scrape#212]
Getting the below error using the latest HEAD code. Seems CloudFlare have made changes again. Thanks in advance for all your hard work on this module!

```
undefined:1
t.charCodeAt(11)
  ^

TypeError: Cannot read property 'charCodeAt' of undefined
    at eval (eval at <anonymous> (evalmachine.<anonymous>:1:4638), <anonymous>:1:3)
    at evalmachine.<anonymous>:1:4638
    at evalmachine.<anonymous>:1:4886
    at Script.runInContext (vm.js:135:20)
    at Script.runInNewContext (vm.js:141:17)
    at Object.runInNewContext (vm.js:307:38)
    at [eval]:1:27
    at Script.runInThisContext (vm.js:124:20)
    at Object.runInThisContext (vm.js:314:38)
    at Object.<anonymous> ([eval]-wrapper:9:26)
ERROR:root:Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.
```

**Comment by pawliczka** [comment]
Same here

**Comment by vosime** [comment]
same for me too

**Comment by BarryThrill** [comment]
Same!

**Comment by vosime** [comment]
mine code started to work again. :-)

**Comment by ozmartian** [comment]
closing this since the issue is now gone... must have been a temporary change/issue @ CloudFlare... everything is working again for me

**Comment by pawliczka** [comment]
Not working for me :( they provided new challenge algorithm
