### ISSUE TITLE
Problem when bypassing cf

### ISSUE THREAD

**Issue by knassar702** [Anorov/cloudflare-scrape#285]
Hello .. when bypassing cf using this code

````
#!/usr/bin/env python
import cfscrape,sys
url=sys.argv[1]
scraper = cfscrape.create_scraper()
print scraper.get(url)
raw_input('\n[!] Continue ..\n')
request = "GET / HTTP/1.1\r\n"
cookie_value, user_agent = cfscrape.get_cookie_string(url)
request += "Cookie: %s\r\nUser-Agent: %s\r\n" % (cookie_value, user_agent)
print request
raw_input('[!] Continue ..\n')
print scraper.get(url).content
````

when run the script .. i show this problem

````
Traceback (most recent call last):
  File "cloudflare.py", line 6, in <module>
    print scraper.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 310, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 120, in request
    resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 279, in request
    resp = self.send(prep, stream=stream, timeout=timeout, verify=verify, cert=cert, proxies=proxies)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 374, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 155, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 69, in get_connection
    if conn.conn_kw.get("ssl_context"):
AttributeError: 'HTTPSConnectionPool' object has no attribute 'conn_kw'

````

Please Help :)

os : kali linux
python ver : 2.7

**Comment by Anorov** [comment]
Please use the bug report issue template.
