### ISSUE TITLE
 redirect_location = urlparse(redirect.headers["Location"]) KeyError: 'location'

### ISSUE THREAD

**Issue by hack4money** [Anorov/cloudflare-scrape#288]
ERROR:root:'https://apkcombo.com//zh-cn/home-design-makeover/in.loop.hdmakeover/download/apk' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "/Users/kk/Code/Python/GPSpider/bypasscf.py", line 11, in <module>
    print scraper.get_tokens("https://apkcombo.com//zh-cn/home-design-makeover/in.loop.hdmakeover/download/apk")
  File "/Library/Python/2.7/site-packages/cfscrape/__init__.py", line 336, in get_tokens
    resp = scraper.get(url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/cfscrape/__init__.py", line 128, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/Library/Python/2.7/site-packages/cfscrape/__init__.py", line 195, in solve_cf_challenge
    redirect_location = urlparse(redirect.headers["Location"])
  File "/Library/Python/2.7/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

**Comment by pro-src** [comment]
Please use the bug report template: https://github.com/Anorov/cloudflare-scrape/issues/new?assignees=&labels=bug&template=bug-report-template.md&title=
