### ISSUE TITLE
使用出错

### ISSUE THREAD

**Issue by remember-python** [Anorov/cloudflare-scrape#314]
Traceback (most recent call last):
  File "/Users/zhangyu/Desktop/asset/domainbrute/test.py", line 9, in <module>
    print scraper.get("http://somesite.com").content  # => "<!DOCTYPE html><html><head>..."
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cfscrape/__init__.py", line 120, in request
    resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 177, in resolve_redirects
    **adapter_kwargs
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 583, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 257, in _get_conn
    return conn or self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 819, in _new_conn
    strict=self.strict, **self.conn_kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 210, in __init__
    timeout=timeout, **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 126, in __init__
    _HTTPConnection.__init__(self, *args, **kw)
TypeError: __init__() got an unexpected keyword argument 'ssl_context'

**Comment by alzamer2** [comment]
hi can you try #315 
and see if it fixed your problem?

**Comment by pl77** [comment]
Here are some instructions if you want help in trying to patch it yourself. 

To find where your `cfscrape` module is stored, the easiest way is with the python interpreter from the environment you want to fix.  Type `python` to open up the interpreter and you'll be greeted with a similar prompt as the one below:

```
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
Type the following two commands:
```python
import importlib
importlib.util.find_spec('cfscrape').origin
```
...which will give you a string path location (similar to the one below): 

`'/home/user/anaconda/lib/python3.7/site-packages/cfscrape/__init__.py'`

Open that file in an editor and replace all the contents with the raw contents from the pull request:

[raw text from pull request 115](https://raw.githubusercontent.com/Anorov/cloudflare-scrape/713e3b4017442d87ad0d638f7991cc330abeee5e/cfscrape/__init__.py)

Save it and your cfscrape should work again.  

Once the pull request is pushed to pypi just update as normal and the contents will be replaced.

**Comment by Anorov** [comment]
This should be fixed in the latest version. Please update with `pip install -U cfscrape`.
