### ISSUE TITLE
Unable to parse Cloudflare anti-bots page: 'NoneType' object has no attribute 'group' Cloudflare may have changed their technique, or there may be a bug in the script.

### ISSUE THREAD

**Issue by witcharrow** [Anorov/cloudflare-scrape#316]
Before creating an issue, first upgrade cfscrape with `pip install -U cfscrape` and see if you're still experiencing the problem. Please also confirm your Node version (`node --version` or `nodejs --version`) is version 10 or higher.

Make sure the website you're having issues with is actually using anti-bot protection by Cloudflare and not a competitor like Imperva Incapsula or Sucuri. And if you're using an anonymizing proxy, a VPN, or Tor, Cloudflare often flags those IPs and may block you or present you with a captcha as a result.

Please **confirm the following statements and check the boxes** before creating an issue:

- [x] I've upgraded cfscrape with `pip install -U cfscrape`
- [x] I'm using Node version 10 or higher
- [x] The site protection I'm having issues with is from Cloudflare
- [x] I'm not using Tor, a VPN, or an anonymizing proxy

## Python version number

Run `python --version` and paste the output below:

```
Python 2.7.12
```

## cfscrape version number

Run `pip show cfscrape` and paste the output below:

```
Name: cfscrape
Version: 1.9.7
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages
Requires: requests
Required-by:
```

## Code snippet involved with the issue

```
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> import cfscrape
>>> cookie_arg, user_agent = cfscrape.get_cookie_string("https://readcomiconline.to/")
ERROR:root:'https://readcomiconline.to/' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cfscrape/__init__.py", line 305, in get_cookie_string
    tokens, user_agent = cls.get_tokens(url, user_agent=user_agent, debug=debug, **kwargs)
  File "cfscrape/__init__.py", line 276, in get_tokens
    resp = scraper.get(url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "cfscrape/__init__.py", line 107, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "cfscrape/__init__.py", line 148, in solve_cf_challenge
    raise ValueError("Unable to parse Cloudflare anti-bots page: {} {}".format(e.message, BUG_REPORT))
ValueError: Unable to parse Cloudflare anti-bots page: 'NoneType' object has no attribute 'group' Cloudflare may have changed their technique, or there may be a bug in the script.

>>> cookie_arg, user_agent = cfscrape.get_cookie_string("https://www.readcomiconline.to/")
ERROR:root:'https://www.readcomiconline.to/' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cfscrape/__init__.py", line 305, in get_cookie_string
    tokens, user_agent = cls.get_tokens(url, user_agent=user_agent, debug=debug, **kwargs)
  File "cfscrape/__init__.py", line 276, in get_tokens
    resp = scraper.get(url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "cfscrape/__init__.py", line 107, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "cfscrape/__init__.py", line 148, in solve_cf_challenge
    raise ValueError("Unable to parse Cloudflare anti-bots page: {} {}".format(e.message, BUG_REPORT))
ValueError: Unable to parse Cloudflare anti-bots page: 'NoneType' object has no attribute 'group' Cloudflare may have changed their technique, or there may be a bug in the script.

>>> quit()
```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```

```

## URL of the Cloudflare-protected page

https://readcomiconline.to/

## URL of Pastebin/Gist with HTML source of protected page

[LINK GOES HERE]

**Comment by Anorov** [comment]
This should be fixed in the latest version. Please update with `pip install -U cfscrape`.
