### ISSUE TITLE
CF protected page loops on request

### ISSUE THREAD

**Issue by ColinTheShark** [Anorov/cloudflare-scrape#328]
Please **confirm the following statements and check the boxes** before creating an issue:

- [x] I've upgraded cfscrape with `pip install -U cfscrape`
- [x] I'm using Node version 10 or higher
- [x] The site protection I'm having issues with is from Cloudflare
- [x] I'm not using Tor, a VPN, or an anonymizing proxy

## Python version number

Run `python --version` and paste the output below:

```
Python 3.7.6
```

## cfscrape version number

Run `pip show cfscrape` and paste the output below:

```
2.0.8
```

## Code snippet involved with the issue

```python
BROWSE = "https://www.furaffinity.net/browse/"
fa = scraper.get(BROWSE, headers=h).content
```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```
PS C:\Users\Shadow\Documents\repositories\hourly-fa> & "C:/Program Files/Python37/python.exe" c:/Users/Shadow/Documents/repositories/hourly-fa/post.py
20-02-22 00:23:26
Traceback (most recent call last):
  File "c:/Users/Shadow/Documents/repositories/hourly-fa/post.py", line 72, in <module>
    main()
    fa = scraper.get(BROWSE, headers=h).content
    return self.request('GET', url, **kwargs)
  File "C:\Users\Shadow\AppData\Roaming\Python\Python37\site-packages\cfscrape\__init__.py", line 128, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "C:\Users\Shadow\AppData\Roaming\Python\Python37\site-packages\cfscrape\__init__.py", line 194, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "C:\Users\Shadow\AppData\Roaming\Python\Python37\site-packages\cfscrape\__init__.py", line 128, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "C:\Users\Shadow\AppData\Roaming\Python\Python37\site-packages\cfscrape\__init__.py", line 194, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "C:\Users\Shadow\AppData\Roaming\Python\Python37\site-packages\cfscrape\__init__.py", line 128, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "C:\Users\Shadow\AppData\Roaming\Python\Python37\site-packages\cfscrape\__init__.py", line 191, in solve_cf_challenge
    time.sleep(max(delay - (time.time() - start_time), 0))
KeyboardInterrupt
```

Alternatively I can wait longer, the request seems to just loop https://nekobin.com/bevunajapa

## URL of the Cloudflare-protected page

https://www.furaffinity.net/browse/

## URL of Pastebin/Gist with HTML source of protected page

Everything within `<section id="gallery-browse">` is dynamic content and updates regularly on refresh.
https://nekobin.com/lasowipico.html

**Comment by lord8266** [comment]
use pull #315
