### ISSUE TITLE
__init__() got an unexpected keyword argument 'ssl_context'

### ISSUE THREAD

**Issue by hi2rashid** [Anorov/cloudflare-scrape#339]
### python3 aa.py 
Traceback (most recent call last):
  File "aa.py", line 5, in <module>
    req = scraper.get('https://example.com')
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 492, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cfscrape/__init__.py", line 121, in request
    resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 480, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 588, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 549, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 251, in _get_conn
    return conn or self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 775, in _new_conn
    strict=self.strict, **self.conn_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 173, in __init__
    timeout=timeout, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 121, in __init__
    _HTTPConnection.__init__(self, *args, **kw)
TypeError: __init__() got an unexpected keyword argument ssl_context

### pip show urllib3 requests

Name: urllib3
Version: 1.13.1
Summary: HTTP library with thread-safe connection pooling, file post, and more.
Home-page: http://urllib3.readthedocs.org/
Author: Andrey Petrov
Author-email: andrey.petrov@shazow.net
License: MIT
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: 
---
Name: requests
Version: 2.9.1
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: cfscrape

### Source Code:

import cfscrape, requests
scraper = cfscrape.create_scraper()
req = scraper.get('https://example.com');
print(req.text)

python3

**Comment by hi2rashid** [comment]
pip3 install -U requests Worked
