### ISSUE TITLE
Error:Cannot get any response from UAM server for long while

### ISSUE THREAD

**Issue by duudukaka** [Anorov/cloudflare-scrape#342]
Before creating an issue, first upgrade cfscrape with `pip install -U cfscrape` and see if you're still experiencing the problem. Please also confirm your Node version (`node --version` or `nodejs --version`) is version 10 or higher.

Make sure the website you're having issues with is actually using anti-bot protection by Cloudflare and not a competitor like Imperva Incapsula or Sucuri. And if you're using an anonymizing proxy, a VPN, or Tor, Cloudflare often flags those IPs and may block you or present you with a captcha as a result.

Please **confirm the following statements and check the boxes** before creating an issue:

- [*] I've upgraded cfscrape with `pip install -U cfscrape`
- [*] I'm using Node version 10 or higher
- [*] The site protection I'm having issues with is from Cloudflare
- [*] I'm not using Tor, a VPN, or an anonymizing proxy

## Python version number

Run `python --version` and paste the output below:

```
Python 3.6.9

```

## cfscrape version number

Run `pip show cfscrape` and paste the output below:

```
Name: cfscrape
Version: 2.1.1
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python3.6/dist-packages
Requires: requests


```

## Code snippet involved with the issue

```
import requests
import socket
import socks
import time
import random
import threading
import sys
import ssl
import datetime
import cfscrape
headers = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36',
               'Connection': 'keep-alive',
        'origin': 'https://www.google.com/'}
scraper = cfscrape.create_scraper()
print (scraper.get("https://xn--i2ru8q2qg.com/code",headers=headers).content)
```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 243, in solve_cf_challenge
    resp = self.request(self.org_method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 219, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 204, in solve_cf_challenge
    answer, delay = self.solve_challenge(body, domain)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 323, in solve_challenge
    universal_newlines=True
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1295, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```

## URL of the Cloudflare-protected page

[https://xn--i2ru8q2qg.com/code]

## URL of Pastebin/Gist with HTML source of protected page

[https://xn--i2ru8q2qg.com/code]

What I met:
```
After submitting this task,I waited for a period with no output,then it outputed wrong code that I put above and I don't know why.
```

**Comment by duudukaka** [comment]
Maybe my IP is backlisted by CF,so I should enter reCAPTCHA code.If I'm right what will it happen?

**Comment by ranyev5** [comment]
Do you have  solved the problem？
I have the same problem as you
