### ISSUE TITLE
ValueError: Unable to identify Cloudflare IUAM Javascript on website

### ISSUE THREAD

**Issue by anfaas1618** [Anorov/cloudflare-scrape#359]
Before creating an issue, first upgrade cfscrape with `pip install -U cfscrape` and see if you're still experiencing the problem. Please also confirm your Node version (`node --version` or `nodejs --version`) is version 10 or higher.

Make sure the website you're having issues with is actually using anti-bot protection by Cloudflare and not a competitor like Imperva Incapsula or Sucuri. And if you're using an anonymizing proxy, a VPN, or Tor, Cloudflare often flags those IPs and may block you or present you with a captcha as a result.

Please **confirm the following statements and check the boxes** before creating an issue:

- [x] I've upgraded cfscrape with `pip install -U cfscrape`
- [x] I'm using Node version 10 or higher
- [x] The site protection I'm having issues with is from Cloudflare
- [x] I'm not using Tor, a VPN, or an anonymizing proxy

## Python version number

Run `python --version` and paste the output below:

```

```

## cfscrape version number

Run `pip show cfscrape` and paste the output below:

```

```

## Code snippet involved with the issue

```

```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```

```

## URL of the Cloudflare-protected page

[LINK GOES HERE]

## URL of Pastebin/Gist with HTML source of protected page

[LINK GOES HERE]

their is error with a specific website : https://soap2day.is/
error:
Traceback (most recent call last):
  File "C:\Users\DRAKH\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cfscrape\__init__.py", line 251, in solve_challenge
    challenge, ms = re.search(
AttributeError: 'NoneType' object has no attribute 'groups'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scrape.py", line 5, in <module>
    html_content=scraper.get(uri).content
  File "C:\Users\DRAKH\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\DRAKH\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cfscrape\__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "C:\Users\DRAKH\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cfscrape\__init__.py", line 204, in solve_cf_challenge
    answer, delay = self.solve_challenge(body, domain)
  File "C:\Users\DRAKH\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cfscrape\__init__.py", line 290, in solve_challenge
    raise ValueError(
ValueError: Unable to identify Cloudflare IUAM Javascript on website. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."

C:\Users\DRAKH\AppData\Local\Programs\Python\Python38-32>

**Comment by FrateSole** [comment]
This error started coming out to me too. I look forward to an update

**Comment by SwapnilSoni1999** [comment]
Having same issue
