### ISSUE TITLE
ValueError: Unable to identify Cloudflare IUAM Javascript on website. Cloudflare may have changed their technique, or there may be a bug in the script.

### ISSUE THREAD

**Issue by zxkang** [Anorov/cloudflare-scrape#367]
Before creating an issue, first upgrade cfscrape with `pip install -U cfscrape` and see if you're still experiencing the problem. Please also confirm your Node version (`node --version` or `nodejs --version`) is version 10 or higher.

Make sure the website you're having issues with is actually using anti-bot protection by Cloudflare and not a competitor like Imperva Incapsula or Sucuri. And if you're using an anonymizing proxy, a VPN, or Tor, Cloudflare often flags those IPs and may block you or present you with a captcha as a result.

Please **confirm the following statements and check the boxes** before creating an issue:

- [ √] I've upgraded cfscrape with `pip install -U cfscrape`
- [ √] I'm using Node version 10 or higher
- [ √] The site protection I'm having issues with is from Cloudflare
- [ √] I'm not using Tor, a VPN, or an anonymizing proxy

## Python version number

Run `python --version` and paste the output below:

```
python -V
Python 2.7.14 :: Anaconda, Inc.
```

## cfscrape version number

Run `pip show cfscrape` and paste the output below:

```
Name: cfscrape
Version: 2.1.1
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: /Users/vivo/anaconda2/lib/python2.7/site-packages
Requires: requests
Required-by:
```

## Code snippet involved with the issue

```
url = "https://tsubasa.im"
proxies = {"http": "http://171.13.24.80:36970"}
tokens, user_agent = cfscrape.get_tokens(url, proxies=proxies)
cookie_arg, user_agent = cfscrape.get_cookie_string(url)
cmd = "curl --cookie {cookie_arg} -A {user_agent} {url}"
print(subprocess.check_output(cmd.format(cookie_arg=cookie_arg, user_agent=user_agent, url=url), shel    l=True))
```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```
ERROR:root:'https://monopoly-one.com/' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    tokens, user_agent = cfscrape.get_tokens(url, proxies=proxies)
  File "/Users/vivo/anaconda2/lib/python2.7/site-packages/cfscrape/__init__.py", line 383, in get_tokens
    resp = scraper.get(url, **kwargs)
  File "/Users/vivo/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Users/vivo/anaconda2/lib/python2.7/site-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/Users/vivo/anaconda2/lib/python2.7/site-packages/cfscrape/__init__.py", line 204, in solve_cf_challenge
    answer, delay = self.solve_challenge(body, domain)
  File "/Users/vivo/anaconda2/lib/python2.7/site-packages/cfscrape/__init__.py", line 292, in solve_challenge
    % BUG_REPORT
ValueError: Unable to identify Cloudflare IUAM Javascript on website. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."
```

## URL of the Cloudflare-protected page

https://tsubasa.im/

## URL of Pastebin/Gist with HTML source of protected page

[LINK GOES HERE]

**Comment by zxkang** [comment]
please, it doesn't work, pls help me.

**Comment by Cosmysd** [comment]
> please, it doesn't work, pls help me.

Nobody can bypass the new challenge
