### ISSUE TITLE
ValueError: Unable to identify Cloudflare IUAM Javascript on website. Cloudflare may have changed their technique

### ISSUE THREAD

**Issue by ishan-biztech** [Anorov/cloudflare-scrape#376]
Please **confirm the following statements and check the boxes** before creating an issue:

- [x] I've upgraded cfscrape with `pip install -U cfscrape`
- [x] I'm using Node version 10 or higher
- [x] The site protection I'm having issues with is from Cloudflare
- [x] I'm not using Tor, a VPN, or an anonymizing proxy

## Python version number

Run `python --version` and paste the output below:

```
Python 3.6.8
```

## cfscrape version number

Run `pip show cfscrape` and paste the output below:

```
Name: cfscrape
Version: 2.1.1
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: /home/user/.local/lib/python3.6/site-packages
Requires: requests
```

## Code snippet involved with the issue

```
scraper = cfscrape.create_scraper(delay=7)

print(scraper.post(self.card_url).content)
```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```
Collecting data for https://www.psacard.com/cert/46420999
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/cfscrape/__init__.py", line 255, in solve_challenge
    javascript, flags=re.S
AttributeError: 'NoneType' object has no attribute 'groups'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cert.py", line 55, in <module>
    pap.scrape()
  File "cert.py", line 31, in scrape
    print(scraper.post(self.card_url).content)
  File "/home/user/.local/lib/python3.6/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/cfscrape/__init__.py", line 204, in solve_cf_challenge
    answer, delay = self.solve_challenge(body, domain)
  File "/home/user/.local/lib/python3.6/site-packages/cfscrape/__init__.py", line 292, in solve_challenge
    % BUG_REPORT
ValueError: Unable to identify Cloudflare IUAM Javascript on website. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."
```

## URL of the Cloudflare-protected page

https://www.psacard.com/cert/46420999

## URL of Pastebin/Gist with HTML source of protected page

Open above link, you'll get it.

**Comment by Sraq-Zit** [comment]
try this #373

**Comment by andress134** [comment]
> try this #373

can't bypass new challenge uam + bot fightr : https://audiograb.net/

**Comment by Sraq-Zit** [comment]
> > try this #373
> 
> can't bypass new challenge uam + bot fightr : https://audiograb.net/

I'm afraid this website uses a challenge completely different from what this module is solving

**Comment by caipenpen** [comment]
I think it already update , I test two site 
https://kissanime.ru and https://www.aichoai.com it have same issues

**Comment by Sraq-Zit** [comment]
That's strange
well at least they are working for me

![image](https://user-images.githubusercontent.com/34834428/86039397-482d0180-ba3a-11ea-8f8a-b1efef51568b.png)

**Comment by 852764** [comment]
> 至少他们为我工作这很奇怪
> 
> ![图片](https://user-images.githubusercontent.com/34834428/86039397-482d0180-ba3a-11ea-8f8a-b1efef51568b.png)

I can't ,why

**Comment by caipenpen** [comment]
> 
> 
> That's strange
> well at least they are working for me
> 
> ![image](https://user-images.githubusercontent.com/34834428/86039397-482d0180-ba3a-11ea-8f8a-b1efef51568b.png)

Yes , You test when they turn off iuam, I already test , if they don't turn on iuam , the code can resolve that .
Example : https://trustsold.com , It don't turn on 5 second load , the code can take token
