### ISSUE TITLE
does not work in python 3

### ISSUE THREAD

**Issue by zoreu** [Anorov/cloudflare-scrape#401]
Before creating an issue, first upgrade cfscrape with `pip install -U cfscrape` and see if you're still experiencing the problem. Please also confirm your Node version (`node --version` or `nodejs --version`) is version 10 or higher.

Make sure the website you're having issues with is actually using anti-bot protection by Cloudflare and not a competitor like Imperva Incapsula or Sucuri. And if you're using an anonymizing proxy, a VPN, or Tor, Cloudflare often flags those IPs and may block you or present you with a captcha as a result.

Please **confirm the following statements and check the boxes** before creating an issue:

- [x ] I've upgraded cfscrape with `pip install -U cfscrape`
- [ ] I'm using Node version 10 or higher
- [ ] The site protection I'm having issues with is from Cloudflare
- [x ] I'm not using Tor, a VPN, or an anonymizing proxy

## Python version number

Run `python --version` and paste the output below:

```
Python 3.8.1
```

## cfscrape version number

Run `pip show cfscrape` and paste the output below:

```
Name: cfscrape
Version: 2.1.1
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: c:\users\joel\appdata\local\programs\python\python38-32\lib\site-packages
Requires: requests
Required-by:

```

## Code snippet involved with the issue

```
import cfscrape
scraper = cfscrape.create_scraper()
print(scraper.get("https://netcine.biz/tvshows/").content)
```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```
Traceback (most recent call last):
  File "C:\Users\Joel\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cfscrape\__init__.py", line 251, in solve_challenge
    challenge, ms = re.search(
AttributeError: 'NoneType' object has no attribute 'groups'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Joel\Desktop\bypass\netcine.py", line 13, in <module>
    print(scraper.get("https://netcine.biz/tvshows/").content)
  File "C:\Users\Joel\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Joel\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cfscrape\__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "C:\Users\Joel\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cfscrape\__init__.py", line 204, in solve_cf_challenge
    answer, delay = self.solve_challenge(body, domain)
  File "C:\Users\Joel\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cfscrape\__init__.py", line 290, in solve_challenge
    raise ValueError(
ValueError: Unable to identify Cloudflare IUAM Javascript on website. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."
```

## URL of the Cloudflare-protected page

https://netcine.biz/tvshows/

## URL of Pastebin/Gist with HTML source of protected page

https://raw.githubusercontent.com/zoreu/zoreu.github.io/master/netcine.txt

**Comment by holabrotato** [comment]
I'm also experiencing the same issue, same version as @zoreu, for a different url.

**Comment by holabrotato** [comment]
I'm seeing the same exact issue

**Comment by sergio49** [comment]
Same issue here with url rlsbb.unblockit.dev
