### ISSUE TITLE
Cloudflare scrape problem

### ISSUE THREAD

**Issue by slava1219** [Anorov/cloudflare-scrape#407]
Before creating an issue, first upgrade cfscrape with `pip install -U cfscrape` and see if you're still experiencing the problem. Please also confirm your Node version (`node --version` or `nodejs --version`) is version 10 or higher.

Make sure the website you're having issues with is actually using anti-bot protection by Cloudflare and not a competitor like Imperva Incapsula or Sucuri. And if you're using an anonymizing proxy, a VPN, or Tor, Cloudflare often flags those IPs and may block you or present you with a captcha as a result.

Please **confirm the following statements and check the boxes** before creating an issue:

- [ ] I've upgraded cfscrape with `pip install -U cfscrape`
- [ ] I'm using Node version 10 or higher
- [ ] The site protection I'm having issues with is from Cloudflare
- [ ] I'm not using Tor, a VPN, or an anonymizing proxy

## Python version number

Run `python --version` and paste the output below:

```
Python 3.8.5
```

## cfscrape version number

Run `pip show cfscrape` and paste the output below:

```
Name: cfscrape
Version: 2.1.1
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: c:\users\a\appdata\local\programs\python\python38-32\lib\site-packages
Requires: requests
Required-by:
```

## Code snippet involved with the issue

```

```

## Complete exception and traceback
ERROR:root:'https://csgo.steamanalyst.com/markets' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "C:\Users\a\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cfscrape\__init__.py", line 251, in solve_challenge
    challenge, ms = re.search(
AttributeError: 'NoneType' object has no attribute 'groups'
(*If the problem doesn't involve an exception being raised, leave this blank*)

```

```

## URL of the Cloudflare-protected page

[LINK GOES HERE]
https://csgo.steamanalyst.com/markets
## URL of Pastebin/Gist with HTML source of protected page
[LINK GOES HERE]
https://csgo.steamanalyst.com/markets

**Comment by slava1219** [comment]
I am scrape from "https://csgo.steamanalyst.com/markets"
Then I have encountered "DDos cloudflare protection"
So I have used "cloudscraper" module then it said that cloudscraper 2.0 is not free.
So I have used "cfscrape" module then it gave me this error:

ERROR:root:'https://csgo.steamanalyst.com/markets' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "C:\Users\a\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cfscrape\__init__.py", line 251, in solve_challenge
    challenge, ms = re.search(
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by FreeGoldRush** [comment]
I'm getting this same error from a different site.  "AttributeError: 'NoneType' object has no attribute 'groups'"

Any help would be appreciated.
