### ISSUE TITLE
ValueError: Unable to identify Cloudflare IUAM Javascript on website. Cloudflare may have changed their technique, or there may be a bug in the script.

### ISSUE THREAD

**Issue by gabrielepinto** [Anorov/cloudflare-scrape#416]
Before creating an issue, first upgrade cfscrape with `pip install -U cfscrape` and see if you're still experiencing the problem. Please also confirm your Node version (`node --version` or `nodejs --version`) is version 10 or higher.

Make sure the website you're having issues with is actually using anti-bot protection by Cloudflare and not a competitor like Imperva Incapsula or Sucuri. And if you're using an anonymizing proxy, a VPN, or Tor, Cloudflare often flags those IPs and may block you or present you with a captcha as a result.

Please **confirm the following statements and check the boxes** before creating an issue:

- [ X] I've upgraded cfscrape with `pip install -U cfscrape`
- [ X] I'm using Node version 10 or higher
- [ X] The site protection I'm having issues with is from Cloudflare
- [ X] I'm not using Tor, a VPN, or an anonymizing proxy

## Python version number

Run `python --version` and paste the output below:

```
Python 3.8.3
```

## cfscrape version number

Run `pip show cfscrape` and paste the output below:

```

Name: cfscrape
Version: 2.1.1
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: d:\anaconda\lib\site-packages
Requires: requests
Required-by: 


```

## Code snippet involved with the issue

```
url="https://ftp.partitodemocratico.it/elezioni_trasparenti/index.html"
session = re.Session()
scraper = cfscrape.create_scraper(sess=session)
m=scraper.get(url)
m
```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
D:\anaconda\lib\site-packages\cfscrape\__init__.py in solve_challenge(self, body, domain)
    250 
--> 251             challenge, ms = re.search(
    252                 r"setTimeout\(function\(\){\s*(var "

AttributeError: 'NoneType' object has no attribute 'groups'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-66-3d78a2930e19> in <module>
      1 session = re.Session()
      2 scraper = cfscrape.create_scraper(sess=session)
----> 3 m=scraper.get(url)
      4 m

D:\anaconda\lib\site-packages\requests\sessions.py in get(self, url, **kwargs)
    553 
    554         kwargs.setdefault('allow_redirects', True)
--> 555         return self.request('GET', url, **kwargs)
    556 
    557     def options(self, url, **kwargs):

D:\anaconda\lib\site-packages\cfscrape\__init__.py in request(self, method, url, *args, **kwargs)
    127         # Check if Cloudflare anti-bot "I'm Under Attack Mode" is enabled
    128         if self.is_cloudflare_iuam_challenge(resp):
--> 129             resp = self.solve_cf_challenge(resp, **kwargs)
    130 
    131         return resp

D:\anaconda\lib\site-packages\cfscrape\__init__.py in solve_cf_challenge(self, resp, **original_kwargs)
    202 
    203         # Solve the Javascript challenge
--> 204         answer, delay = self.solve_challenge(body, domain)
    205         if method == 'POST':
    206             cloudflare_kwargs["data"]["jschl_answer"] = answer

D:\anaconda\lib\site-packages\cfscrape\__init__.py in solve_challenge(self, body, domain)
    288             delay = self.delay or (float(ms) / float(1000) if ms else 8)
    289         except Exception:
--> 290             raise ValueError(
    291                 "Unable to identify Cloudflare IUAM Javascript on website. %s"
    292                 % BUG_REPORT

ValueError: Unable to identify Cloudflare IUAM Javascript on website. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."
```

## URL of the Cloudflare-protected page

[https://ftp.partitodemocratico.it/elezioni_trasparenti/index.html]

## URL of Pastebin/Gist with HTML source of protected page

[<!DOCTYPE HTML>
<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="shortcut icon" href="favicon.ico">         
     <title>Elezioni trasparenti - Partito Democratico</title> 
    <link rel='stylesheet' href='common.css' type='text/css' />    
    <link href="candidati.json" rel="exhibit-data" type="application/json" />
    <link href="types.js" rel="exhibit-data" type="application/json" />
    
    <script src="3.1.2rc2/exhibit-api.js?locale=fr"></script>
    <style>
        #main-layout {height: 100%; }
        #logo { padding: 0.7em; background:#fff; }
        #left-column { padding: 1em; width: 20em; min-width:  20em !important; background: #eee; }
        #main-column { padding: 2em; vertical-align: top; }
        div.thumbnail-lens { width: 450px; height: 180px; overflow: hidden; margin-right: 20px; margin-bottom: 20px; border: 1px solid #ccc; }
        div.exhibit-flowingFacet {margin-top: 10px; padding: 10px; background: white; }
        h3 { margin-top: 0px; margin-bottom: 0px; font-size: 1.4rem}
        h1 { display:none !important; margin-top: 0px;}
        h2.title { text-align: center;font-size: 2em!important;}
        img.exhibit-toolboxWidget-button { cursor: pointer; margin: 0 1px; display:none !important; }
        .elezione { color:#cc0000; font-size: 1.4rem; font-family: Arial, Helvetica, sans-serif; }
        .collegio2 { font-size: 1.3rem; color:#000;font-weight: bold;}
        .circoscrizione { color:#333; font-size: 1.3rem; font-family: Arial, Helvetica, sans-serif; }
        .desc_circ { color:#444; font-size: 1.1rem; font-family: Arial, Helvetica, sans-serif; }
    </style>
  </head>
  <body>
     <div id="logo"><a href="https://www.partitodemocratico.it"><img src="images/logo-pd.jpg" alt="Logo PD"/></a></div>
     <h2 class="title">Elezioni trasparenti</h2>
     <div data-ex-role="collection" data-ex-item-types="candidato"></div>
    <table border="0" cellpadding="0" cellspacing="0" id="main-layout" width="100%">
      <tr>
        <td id="main-column">          
          <div data-ex-role="lens" class="thumbnail-lens" data-ex-item-types="candidato">
            <table cellspacing="5">
              <tr><td>
                <h3 data-ex-content=".name"></h3>
                <table>
                  <tr><td><span class="elezione">Elezioni</span> <span data-ex-content=".elezioni" class="elezione"></span> <span data-ex-content=".anno" class="elezione"></span> - <span data-ex-content=".data" class="elezione"></span></td></tr>                  
                  <tr><td><span class="collegio2">Candidato</span> <span data-ex-content=".candidato" class="collegio2"></span>                  
                  <div class="circoscrizione"><span data-ex-content=".circoscrizioneC" class="circoscrizione"></span></div>                  
                  <div class="circoscrizione"><span data-ex-content=".circoscrizione" class="circoscrizione"></span><br> <span data-ex-content=".desc_circ" class="desc_circ"></span></div>                  
                  <div class="collegio"><tr><td><span data-ex-content=".collegiou"></span></div>
                  <div class="circoscrizione"><tr><td><span data-ex-content=".comune"></span></div>
                  <div class="circoscrizione"><tr><td><span data-ex-content=".provincia"></span></div>
                  <div class="circoscrizione"><tr><td><span data-ex-content=".regione"></span></div>
                  <tr><td><a data-ex-href-content=".cv" target="_blank">Curriculum Vitae</a> - <a data-ex-href-content=".cp" target="_blank">Certificato penale</a></td></tr>
                </table>
              </td></tr>
            </table>
          </div>
          <div id="the-views"><div data-ex-role="view" data-ex-view-class="Thumbnail" id="view1211341960556"></div></div>
        </td>
        <div align="right"><a href="https://www.simile-widgets.org/exhibit/"><img src="images/exhibit-small-DeepSkyBlue.png"></a></div>
        <div data-ex-role="exhibit-controlPanel" data-ex-show-bookmark="true" data-ex-developer-mode="false" data-ex-hover-reveal="true">
        
        
        <td id="left-column" width="50%">        
          <div id="the-facets2">
          <h3>Cerca:</h3>
            <div data-ex-facet-class="TextSearch" data-ex-facetlabel="Search" data-ex-role="facet" id="facet1211341960513"></div>
            <div data-ex-role="facet" 
            	data-ex-expression=".anno" 
                data-ex-facet-label="per anno" 
                data-ex-scroll="false" 
                data-ex-show-missing="false"
                data-ex-sort-mode="value">
            </div>
            <div data-ex-role="facet" 
            	data-ex-expression=".elezioni" 
                data-ex-facet-label="per elezione" 
                data-ex-scroll="false" 
                data-ex-show-missing="false"
                data-ex-sort-mode="value">
            </div>
            <div data-ex-role="facet" 
            	data-ex-expression=".data" 
                data-ex-facet-label="per data" 
                data-ex-scroll="false" 
                data-ex-show-missing="false"
                data-ex-sort-mode="value">
            </div>
            <div data-ex-role="facet" 
            	data-ex-expression=".collegiou" 
                data-ex-facet-label="per collegio unin." 
                data-ex-scroll="false" 
                data-ex-show-missing="false"
                data-ex-sort-mode="value">
            </div>
            <div data-ex-role="facet" 
            	data-ex-expression=".collegiop" 
                data-ex-facet-label="per collegio plurin." 
                data-ex-scroll="false" 
                data-ex-show-missing="false"
                data-ex-sort-mode="value">
            </div>
        </td><td id="left-column" width="50%">
          <div id="the-facets3">
            <div data-ex-role="facet" 
            	data-ex-expression=".regione" 
                data-ex-facet-label="per regione" 
                data-ex-scroll="false" 
                data-ex-show-missing="false"
                data-ex-sort-mode="value">
            </div>
            <div data-ex-role="facet" 
            	data-ex-expression=".provincia" 
                data-ex-facet-label="per provincia" 
                data-ex-scroll="false" 
                data-ex-show-missing="false"
                data-ex-sort-mode="value">
            </div>
            <div data-ex-role="facet" 
            	data-ex-expression=".comune" 
                data-ex-facet-label="per comune" 
                data-ex-scroll="false" 
                data-ex-show-missing="false"
                data-ex-sort-mode="value">
            </div>
            <div data-ex-role="facet" 
            	data-ex-expression=".circoscrizione" 
                data-ex-facet-label="per circoscrizione" 
                data-ex-scroll="false" 
                data-ex-show-missing="false"
                data-ex-sort-mode="value">
            </div>
            <div data-ex-role="facet" 
            	data-ex-expression=".circoscrizioneC" 
                data-ex-facet-label="per circoscrizione/municipio" 
                data-ex-scroll="false" 
                data-ex-show-missing="false"
                data-ex-sort-mode="value">
            </div>
        </td>
       </tr>
    </table>
  </body>
</html>]

**Comment by rusq** [comment]
Trying to get the RBNZ rates excel file with cloud scraper also results in this error message:
```python
import cfscrape

URL="https://www.rbnz.govt.nz/-/media/ReserveBank/Files/Statistics/tables/b1/hb1-daily.xlsx"

scraper = cfscrape.create_scraper()

with open("dump.bin", "wb") as f:
    f.write(scraper.get(URL).content)
```
```
(.venv) [1:wf/personal/rbcf> pip show cfscrape
Name: cfscrape
Version: 2.1.1
```

```
(.venv) [0:wf/personal/rbcf> python rbnz.py 
Traceback (most recent call last):
  File "/Users/x/wf/personal/rbcf/.venv/lib/python3.8/site-packages/cfscrape/__init__.py", line 251, in solve_challenge
    challenge, ms = re.search(
AttributeError: 'NoneType' object has no attribute 'groups'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rbnz.py", line 8, in <module>
    f.write(scraper.get(URL).content)
  File "/Users/x/wf/personal/rbcf/.venv/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Users/x/wf/personal/rbcf/.venv/lib/python3.8/site-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/Users/x/wf/personal/rbcf/.venv/lib/python3.8/site-packages/cfscrape/__init__.py", line 204, in solve_cf_challenge
    answer, delay = self.solve_challenge(body, domain)
  File "/Users/x/wf/personal/rbcf/.venv/lib/python3.8/site-packages/cfscrape/__init__.py", line 290, in solve_challenge
    raise ValueError(
ValueError: Unable to identify Cloudflare IUAM Javascript on website. Cloudflare may have changed their technique, or there may be a bug in the script.

**Comment by vo11** [comment]
Trying to parse https://hidemy.name/ for proxies

**Comment by pvolkovq** [comment]
Trying to parse https://hidemy.name/ for proxies  with cfscrape and getting an exception
    
   Versions:
```
Python 3.9.2
node v15.12.0
cfscrape 2.1.1
```

```python
import cfscrape

scraper = cfscrape.create_scraper()
headers = {
"user-agent": UserAgent().random
}

def get_pages_count():
url = 'https://hidemy.name/en/proxy-list/#list'
r = scraper.get(url, headers=headers).text
```
**Exception**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cfscrape/__init__.py", line 251, in solve_challenge
    challenge, ms = re.search(
AttributeError: 'NoneType' object has no attribute 'groups'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pavelvolkov/ma_work/ma_services/proxy_collector/scripts/hidemyname.py", line 117, in <module>
    parse(0, {})
  File "/Users/pavelvolkov/ma_work/ma_services/proxy_collector/scripts/hidemyname.py", line 97, in parse
    links = get_pages_count()
  File "/Users/pavelvolkov/ma_work/ma_services/proxy_collector/scripts/hidemyname.py", line 21, in get_pages_count
    r = scraper.get(url, headers=headers).text
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cfscrape/__init__.py", line 204, in solve_cf_challenge
    answer, delay = self.solve_challenge(body, domain)
  File "/usr/local/lib/python3.9/site-packages/cfscrape/__init__.py", line 290, in solve_challenge
    raise ValueError(
ValueError: Unable to identify Cloudflare IUAM Javascript on website. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."
```

**Comment by SpangleLabs** [comment]
Yeah, it's broken, see #406
