### ISSUE TITLE
HTTP Error 521

### ISSUE THREAD

**Issue by xiuyanduan** [Anorov/cloudflare-scrape#45]
I want to get the content of [http://www.eoemarket.com/soft/28366.html](http://www.eoemarket.com/soft/28366.html) 
* when I used `urllib2` in `Python`,the error is
```python
Traceback (most recent call last):
  File "5_youyishichang.py", line 7, in <module>
    html=urllib2.urlopen(url).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 521: 
```
* when I used `curl www.eoemarket.com/soft/28366.html -v`,the stdout is
```
* Hostname was NOT found in DNS cache
*   Trying 115.231.25.180...
* Connected to www.eoemarket.com (115.231.25.180) port 80 (#0)
> GET /soft/28366.html HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.eoemarket.com
> Accept: */*
> 
< HTTP/1.1 521 
< Date: Thu, 07 Apr 2016 08:41:58 GMT
< Content-Type: text/html
< Content-Length: 1009
< Connection: keep-alive
< Cache-Control: no-cache, no-store
* Server YUNDUN is not blacklisted
< Server: YUNDUN
< X-Cache:  from YUNDUN
< 
* Connection #0 to host www.eoemarket.com left intact
<html><body><script language="javascript"> window.onload=setTimeout("ix(107)", 200); function ix(QG) {var qo, mo="", no="", oo = [0x16,0x94,0x38,0x80,0x28,0x80,0x57,0xc8,0x0b,0x33,0x8b,0xa3,0x9b,0x44,0xfd,0x76,0xce,0x15,0x4a,0x4e,0xa2,0x39,0x52,0xaa,0x72,0x19,0x6d,0x72,0x17,0x7c,0x8f,0x54,0x17,0x5b,0xc3,0xc1,0x6a,0xa2,0xca,0x1e,0x95,0x4e,0xa6,0xee,0x96,0x4d,0x95,0xca,0x2e,0x80,0x43,0xb8,0x7b,0xe0,0x98,0x5b,0x19,0x7e,0x46,0xa9,0x7e,0xf1,0xd6,0x85,0x9a,0x0e,0x21,0x39,0x01,0x76,0xa6,0x0d,0x22];qo = "qo=71; do{oo[qo]=(-oo[qo])&0xff; oo[qo]=(((oo[qo]>>1)|((oo[qo]<<7)&0xff))-160)&0xff;}while(--qo>=2);"; eval(qo);qo = 70; do { oo[qo] = (oo[qo] - oo[qo - 1]) & 0xff; } while (-- qo >= 3 );qo = 1; for (;;) { if (qo > 70) break; oo[qo] = ((((((oo[qo] + 135) & 0xff) + 197) & 0xff) << 5) & 0xff) | (((((oo[qo] + 135) & 0xff) + 197) & 0xff) >> 3);qo++;}po = "";for (qo = 1; qo < oo.length - 1; qo++) if (qo % 7) po += String.fromCharCode(oo[qo] ^ QG);po += "\""; eval("qo=eval;qo(po);");}</script> </body></html>
```
* I search "http error 521" and get this url: [Error 521: Web server is down](https://support.cloudflare.com/hc/en-us/articles/200171916-Error-521-Web-server-is-down) in cloudflare's official website.
It seems this modules cloudflare-scrape could solve this problem,but it didn't return the entire html.
If I use a browser such as Chrome, I could get the entire html.
* `pip list` of my virtualenv
```
argparse (1.2.1)
cfscrape (1.6.1)
pip (1.5.4)
PyExecJS (1.3.1)
requests (2.9.1)
setuptools (2.2)
six (1.10.0)
wsgiref (0.1.2)
```
`nodejs -v` is `v0.10.37`
But when I execute 
```python
import cfscrape
scraper = cfscrape.create_scraper()
url="http://www.eoemarket.com/soft/28366.html"
scraper.get(url).content
```
It's same as the output of `curl`.
I am a rookie about `Python` ,and my English is poor. Looking forward to your reply.Thank you very much. ^_^

**Comment by Anorov** [comment]
This just means Cloudflare can't reach the web server.

**Comment by nmakarun** [comment]
@Anorov, @Srednogorie. I am facing similar issue could you please let know if there are any workaround for this error. It would be really helpful.
