### ISSUE TITLE
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_'

### ISSUE THREAD

**Issue by CureSaba** [Anorov/cloudflare-scrape#467]
Before creating an issue, first upgrade cfscrape with `pip install -U cfscrape` and see if you're still experiencing the problem. Please also confirm your Node version (`node --version` or `nodejs --version`) is version 10 or higher.

Make sure the website you're having issues with is actually using anti-bot protection by Cloudflare and not a competitor like Imperva Incapsula or Sucuri. And if you're using an anonymizing proxy, a VPN, or Tor, Cloudflare often flags those IPs and may block you or present you with a captcha as a result.

Please **confirm the following statements and check the boxes** before creating an issue:

- [x ] I've upgraded cfscrape with `pip install -U cfscrape`
- [x ] I'm using Node version 10 or higher
- [x ] The site protection I'm having issues with is from Cloudflare
- [x ] I'm not using Tor, a VPN, or an anonymizing proxy

## Python version number

Run `python --version` and paste the output below:

```
Python 3.12.1
```

## cfscrape version number

Run `pip show cfscrape` and paste the output below:

```
Name: cfscrape
Version: 2.1.1
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: C:\Users\CureSaba\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires: requests
Required-by:
```

## Code snippet involved with the issue

```
from urllib3.util.ssl_ import create_urllib3_context, DEFAULT_CIPHERS
```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```
Traceback (most recent call last):
  File "c:\Users\CureSaba\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\CureSaba\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\CureSaba\.vscode\extensions\ms-python.debugpy-2024.8.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>       
    cli.main()
  File "c:\Users\CureSaba\.vscode\extensions\ms-python.debugpy-2024.8.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\CureSaba\.vscode\extensions\ms-python.debugpy-2024.8.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\CureSaba\.vscode\extensions\ms-python.debugpy-2024.8.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\CureSaba\.vscode\extensions\ms-python.debugpy-2024.8.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code       
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\CureSaba\.vscode\extensions\ms-python.debugpy-2024.8.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "C:\Users\CureSaba\Downloads\a\test.py", line 1, in <module>
    import cfscrape
  File "c:\Users\CureSaba\AppData\Local\Programs\Python\Python312\Lib\site-packages\cfscrape\__init__.py", line 19, in <module>
    from urllib3.util.ssl_ import create_urllib3_context, DEFAULT_CIPHERS
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (c:\Users\CureSaba\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\ssl_.py)
```

## URL of the Cloudflare-protected page

[https://twivideo.net/?ranking]

## URL of Pastebin/Gist with HTML source of protected page

[https://twivideo.net/?ranking]

**Comment by chriss2401** [comment]
Any solutions here ? I am also having the same issue.

**Comment by yieldcurvemonkey** [comment]
try downgrading urllib3

`pip install urllib3==1.26.16`

**Comment by rianaditro** [comment]
> pip install urllib3==1.26.16

It does remove the problem but unfortunately cant bypass cloudflare protection

**Comment by aviatorhh** [comment]
> try downgrading urllib3
> 
> `pip install urllib3==1.26.16`

Does not help if you need 3.2

**Comment by manl154557-source** [comment]
OMG 😱 Everyone scraping Google is doing it WRONG! Your results are garbage without this. Join the Telegram updates NOW: https://t.me/OpenSerp — you’ll see the real hacks and fixes before anyone else!
