### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by Pr0xy671** [Anorov/cloudflare-scrape#54]
Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "C:\Python27\lib\site-packages\requests\sessions.py", line 487, in get
	    return self.request('GET', url, **kwargs)
	  File "C:\Python27\lib\site-packages\cfscrape\__init__.py", line 30, in request
	    return self.solve_cf_challenge(resp, **kwargs)
	  File "C:\Python27\lib\site-packages\cfscrape\__init__.py", line 52, in solve_cf_challenge
	    js = self.extract_js(body)
	  File "C:\Python27\lib\site-packages\cfscrape\__init__.py", line 73, in extract_js
	    "t,r,a,f.+?\r?\n[\s\S]+?a\.value =.+?)\r?\n", body).group(1)
	AttributeError: 'NoneType' object has no attribute 'group'

URL: 
http://section-f.tk/

HTML source of website: 
https://gist.github.com/Pr0xy671/73853aa0e858396651c8b75404075e53

**Comment by Coriou** [comment]
Same for me

**Comment by Anorov** [comment]
Fixed version has been pushed to PyPI.
