### ISSUE TITLE
Not working with "get" URL

### ISSUE THREAD

**Issue by gbozzetti** [Anorov/cloudflare-scrape#61]
No answer from URL with "get" format, with the "normal" URL is working.

i.e. http://cb01.co is working - http://cb01.co/?s=chocolat not working.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 30, in request
    return self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 69, in solve_cf_challenge
    return self.get(submit_url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 30, in request
    return self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 69, in solve_cf_challenge
    return self.get(submit_url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 30, in request
    return self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 69, in solve_cf_challenge
    return self.get(submit_url, **kwargs)
(and so on....)

HTML: http://pastebin.com/jvZRbaYF

**Comment by Anorov** [comment]
See https://github.com/Anorov/cloudflare-scrape/issues/60.
