### ISSUE TITLE
Has cloudfare code been changed?

### ISSUE THREAD

**Issue by AbsoluteZero273** [Anorov/cloudflare-scrape#65]
Source code for the webpage: http://pastebin.com/YAhwjGGu
Website url: https://kissanime.to/

Actual error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "Gui.py", line 61, in scrape
    self.scraper.login("username", "password")
  File "/home/absolutezero273/Desktop/Projects/PyKissDl/PyKissDl/scraper.py", line 30, in login
    login_form.find('input', {'name': 'username'})['value'] = usr
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by dcambria** [comment]
Error here, same sources as @AbsoluteZero273
Tks.
```
[!] Unable to parse Cloudflare anti-bots page. Try upgrading cloudflare-scrape, or submit a bug report if you are running the latest version. Please read https://github.com/Anorov/cloudflare-scrape#updates before submitting a bug report.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cfscrape/__init__.py", line 38, in request
    return self.solve_cf_challenge(resp, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cfscrape/__init__.py", line 60, in solve_cf_challenge
    js = self.extract_js(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cfscrape/__init__.py", line 89, in extract_js
    if "Node" in self.js_engine:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by Anorov** [comment]
@dcambria Can I see the full code you're using?

@AbsoluteZero273 I suspect this is due to a change in that particular website. Cloudflare's code hasn't changed.

**Comment by Twoure** [comment]
To chime in, I parse the kissanime site just fine after `v1.6.5` update.  Could be an issue other than `cfscrape`.  For instance the latest `PyExecJS` (`v1.4.0`) has issues with cross platform compatibility.  I've found the `v1.1.0` to be the most universal across multiple platforms.  Also it is best to keep an up-to-date `requests` lib, as some of the older versions have issues with kissanime.

**Comment by AbsoluteZero273** [comment]
@Twoure It was working fine before. I have my `requests` lib updated till date. So, should I downgrade `PyExecJs`?

**Comment by AbsoluteZero273** [comment]
Nevermind. After I updated to `v1.6.5` update, it's working fine now. I will be closing this issue now. Thank you all.

**Comment by dcambria** [comment]
Thank you!

**Comment by dcambria** [comment]
uhn... no donuts for me, ehehe
```
>>> import cfscrape
>>> scraper = cfscrape.create_scraper()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cfscrape/__init__.py", line 109, in create_scraper
    "such as Node, call create_scraper(js_engine=\"Node\")" % js_engine)
EnvironmentError: Your Javascript runtime 'JavaScriptCore' is not supported due to security concerns. Please use Node.js or PyV8. To force a specific engine, such as Node, call create_scraper(js_engine="Node")

```

**Comment by dcambria** [comment]
Then, tried with
```
>>> scraper = cfscrape.CloudflareScraper()
```

and...

```
>>> print scraper.get("http://xxxxxxxxxx").content
[!] Unable to parse Cloudflare anti-bots page. Try upgrading cloudflare-scrape, or submit a bug report if you are running the latest version. Please read https://github.com/Anorov/cloudflare-scrape#updates before submitting a bug report.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cfscrape/__init__.py", line 38, in request
    return self.solve_cf_challenge(resp, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cfscrape/__init__.py", line 60, in solve_cf_challenge
    js = self.extract_js(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cfscrape/__init__.py", line 89, in extract_js
    if "Node" in self.js_engine:
TypeError: argument of type 'NoneType' is not iterable
>>> 

```

**Comment by Twoure** [comment]
@dcambria the error states that you cannot use `JavaScriptCore` as a JavaScript Runtime Engine.
Taken from the [Readme](https://github.com/Anorov/cloudflare-scrape#cloudflare-scrape):
> The only supported Javascript engines at this time are Node.js and PyV8. This is due to potential security concerns with the other engines.
