### ISSUE TITLE
This doesn't work on kissanime.to anymore.

### ISSUE THREAD

**Issue by Wicloz** [Anorov/cloudflare-scrape#74]
This worked perfectly until a few weeks ago, when it suddenly stoppen working. I tried updating and even using a different system, but it gives the same error every time. From this I can conclude that cloudflare changed their security and this needs to be updated.

Error message:
```
Traceback (most recent call last):
  File "C:\xampp7.0\htdocs\app\AnimeSentinel/CloudFlare.py", line 7, in <module>
    cookie_arg, user_agent = cfscrape.get_cookie_string(sys.argv[1])
  File "C:\Users\WilcoDeBoer\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cfscrape\__init__.py", line 146, in get_cookie_string
    tokens, user_agent = cls.get_tokens(url, user_agent=user_agent)
  File "C:\Users\WilcoDeBoer\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cfscrape\__init__.py", line 118, in get_tokens
    resp = scraper.get(url)
  File "C:\Users\WilcoDeBoer\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 483, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\WilcoDeBoer\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cfscrape\__init__.py", line 37, in request
    return self.solve_cf_challenge(resp, **kwargs)
  File "C:\Users\WilcoDeBoer\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cfscrape\__init__.py", line 77, in solve_cf_challenge
    return self.get(submit_url, **kwargs)
  File "C:\Users\WilcoDeBoer\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 483, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\WilcoDeBoer\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cfscrape\__init__.py", line 37, in request
    return self.solve_cf_challenge(resp, **kwargs)
  File "C:\Users\WilcoDeBoer\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cfscrape\__init__.py", line 55, in solve_cf_challenge
    params["jschl_vc"] = re.search(r'name="jschl_vc" value="(\w+)"', body).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Coriou** [comment]
On which site are you experiencing this error ? For me, it's still working as expected on all sites I use it on.

**Comment by Wicloz** [comment]
I have only tried kissanime.to. Let me check some other sites.

**Comment by Wicloz** [comment]
It is indeed working on other sites for me.

**Comment by Wicloz** [comment]
Nevermind, it does work on kissanime.to, the issue is somewhere else.
